### PR TITLE
Anonymized Collaborative documents

### PR DESCRIPTION
**Pull request by Sabryr**
Anonymized Collaborative document

### CODE REVIEW

**Comment by bast** [comment]
The hackmd files need a `permalink` metadata like in [this example](https://raw.githubusercontent.com/coderefinery/2020-11-17-online/gh-pages/hackmd-day1.md) otherwise the workshop page will link to 404.

**Comment by Sabryr** [comment]
Thank you @bast , see whether this would fix it

**Comment by bast** [comment]
The second one does not render, there is a blank line too much.

**Comment by bast** [comment]
Followed-up in #37.

**Pull request merged**
