### PR TITLE
reorder schedule after discussing with Richard

### PR DESCRIPTION
**Pull request by bast**

### CODE REVIEW

**Review by rkdarst — APPROVED** [review]
I approve of this; how many others need to be checked with?  I think we can do it though, we discussed in chat and there aren't many other options.

**Comment by Sabryr** [comment]
May be @annefou should check if she is OK with this

**Comment by annefou** [comment]
I am OK with it except that I cannot teach on Tuesday,

**Comment by bast** [comment]
Merging. We need to somehow load-balance the sessions. I think thematically they make sense. Perhaps Anne can help us drafting the assignment for the day 2 exercises: what to be careful about, what not to forget.

**Pull request merged**
